name: 03 Workflow Runners

on: push

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: |
          echo "Running on Ubuntu"
          echo "Runner OS: $RUNNER_OS"
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Say OS
        run: |
          echo "Running on Windows"
          echo "Runner OS: $RUNNER_OS"
  macos-echo:
    runs-on: macos-latest
    steps:
      - name: Say OS
        run: |
          echo "Running on macOS"
          echo "Runner OS: $RUNNER_OS"