name: 06 - Contexts
run-name: 06 - Context | DEBUG - ${{ inputs.debug }}

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
        description: "Enable debug mode"

env:
  MY_WORKFLOW_VAR: "WORKFLOW"
  MY_OVERRITTEN_VAR: "OVERRIDDEN"

jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_JOB_VAR: "VARIABLE"
      MY_OVERRITTEN_VAR: "OVERRIDDEN 2"

    steps:
      - name: Display information
        run: |
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Job ID: ${{ github.job }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
      - name: Retrive variables
        run: |
          echo "Variable value: ${{ vars.MY_VAR }}"
      - name: Print environment variables
        env:
          MY_OVERRITTEN_VAR: "OVERRIDDEN 3"
        run: |
          echo "Workflow Variable: ${{ env.MY_WORKFLOW_VAR }}"
          echo "Job Variable: ${{ env.MY_JOB_VAR }}"
          echo "Overridden Variable: ${{ env.MY_OVERRITTEN_VAR }}"
      - name: Print env variables
        run: |
          echo "Workflow Variable: ${{ env.MY_WORKFLOW_VAR }}"
          echo "Environment Variables: ${{ env.MY_OVERRITTEN_VAR }}"

  echo-data2:
    runs-on: ubuntu-latest
    steps:
      - name: Print env variables
        run: |
          echo "Workflow Variable: $MY_WORKFLOW_VAR"
          echo "Overridden Variable: $MY_OVERRITTEN_VAR"
