name: 08 - Using Variables

on:
  push:
  workflow_dispatch:

env:
  WORKFLOW_VAR: "I am workflow env var"
  OVERWRITTEN: "WORKFLOW"

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "I am a job env var"
      OVERWRITTEN: "JOBS"
    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: 'I am a step en var'
          step_var2: 'I am another step env var'
        run: |
          echo "Step env var: ${{env.STEP_VAR}}"
          echo "Step env var 2: $step_var2"
          echo "Job env var: $JOB_VAR"
          echo "Job env var: $WORKFLOW_VAR"
          echo "Overwritten env var: $OVERWRITTEN"
      - name: Overwritten variables
        env:
          OVERWRITTEN: "STEP"
        run: |
          echo "Overwritten env var: $OVERWRITTEN"

  echo2:
    runs-on: ubuntu-latest
    steps:
      - name: Print env overriten variables
        run: |
          echo "Overwritten env var: $OVERWRITTEN"