name: 16 - Working with Environments

on:
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    env:
      my-env-variable: ${{vars.MY_ENV_VALUE || 'default value'}}
    steps:
      - name: Echo vars
        run: |
          echo "Deploying staging"
  e2e-test:
    runs-on: ubuntu-latest
    needs:
      - deploy-staging
    steps:
      - name: E2E Tests
        run: |
          echo "Running E2E test"
  deploy-prod:
    runs-on: ubuntu-latest
    needs:
      - e2e-test
    environment: prod
    env:
      my-env-variable: ${{vars.MY_ENV_VALUE || 'default value'}}
    steps:
      - name: Echo vars
        run: |
          echo "Deploying prod"