name: 17 - 2 - Custom actions - JS
run-name: '17 - 2 - Custom actions - JS | BB: ${{inputs.base-branch}} | TB: ${{inputs.target-branch}} | WD: ${{inputs.working-directory}}'

on:
  workflow_dispatch:
    inputs:
      base-branch:
        description: Base branch for to the dependecy update checks
        default: main
        type: string
      target-branch:
        description: Target branch to create the PR is created
        default: update-dependencies
        type: string
      working-directory:
        description: Working directory to run the action
        default: 17-custom-actions/react-app
        type: string
      debug:
        description: Enable debug mode
        default: false
        type: boolean
permissions:
  contents: write
  pull-requests: write
jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checck for dependency updates
        id: update-deps
        uses: ./.github/actions/js-dependency-update
        with:
          base-branch: ${{ inputs.base-branch }}
          head-branch: ${{ inputs.target-branch }}
          working-directory: ${{ inputs.working-directory }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          debug: ${{ inputs.debug }}
      - name: Print custom action output
        run: |
          echo "Updates available: ${{ steps.update-deps.outputs.updates-available }}"