name: 17 - 3 - Custom actions - Docker

on:
  workflow_dispatch:
    inputs:
      url:
        description: Base branch for to the dependecy update checks
        options:
          - 'https://www.google.com'
          - 'https://www.github-ivalid-url-unreachable-never-used.com'
          - 'thisurldoesnotexist12345'
        type: choice
      max_retries:
        description: Maximum number of retries
        default: '10'
        required: false
      delay:
        description: Interval between retries in milliseconds
        default: '5'
        required: false
permissions:
  contents: write
  pull-requests: write
jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
          max_retries: ${{inputs.max_retries}}
          delay: ${{inputs.delay}}